Issue 529/collection form
enonic/app-explorer pull request #530
Opened 2022-06-14 12:11 UTC by ComLock

2022-06-16 12:11 UTC, alansemenov commented on src/main/resources/assets/react/collection/DocumentTypeSelector.tsx
> +		memoizedQueryDocumentTypes
Same here.

2022-06-16 12:16 UTC, alansemenov requested changes

2022-06-17 07:27 UTC, ComLock commented on src/main/resources/assets/react/collection/useCollectionState.ts
> +		}
Yeah, this was only for debugging anyway. All those can be one effect.

2022-06-17 07:51 UTC, alansemenov approved these changes

2022-06-17 07:53 UTC, merged