Fix generation sourceJar after upgrade default plugin #625
enonic/app-explorer pull request #626
Opened 2022-11-02 11:44 UTC by anatol-sialitski

2022-11-02 12:09 UTC, rymsha requested changes
Maybe better to not add source files twice?

2022-11-02 12:31 UTC, rymsha approved these changes

2022-11-03 08:17 UTC, ComLock approved these changes

2022-11-03 08:17 UTC, ComLock commented on build.gradle
> -		java {
I probably copied this section from somewhere, I have no idea what it does, so as long as the app works, it's A OK to me.

2022-11-03 08:49 UTC, merged